root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/sanqa-suq-srv"
  bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp"]
  exclude_file = ["*_test.go"]
  follow_symlink = true
  delay = 200

[log]
  time = true
