name: sanqa-suq
services:
  app: 
    build:
      context: ./ 
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    depends_on:
      - postgres
  postgres: 
    image: postgres:latest  
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
